services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ['CMD', 'bash', '-c', "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - marketingestion

  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_CONFLUENT_LICENSE: ' '
    healthcheck:
      test: ['CMD', 'bash', '-c', "nc -z localhost 9092"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - marketingestion

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - marketingestion

  kafka-topic-init:
    build: 
      context: .
      dockerfile: scripts/Dockerfile.kafka-topic
    env_file:
      - .env
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - marketingestion
    restart: "no"

  minio-bucket-init:
    build: 
      context: .
      dockerfile: scripts/Dockerfile.minio-bucket
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - marketingestion
    restart: "no"

  spark:
    build: 
      context: ./spark_jobs
      dockerfile: Dockerfile 
    env_file:
      - .env
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - minio
    ports:
      -"7077:7077"
      - "4040:4040"
    volumes:
      - ./spark_jobs/jobs:/opt/bitnami/spark/jobs
      - ./data/minio:/data
    command: sleep infinity
    networks:
      - marketingestion

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-marketdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marketingestion

  x-airflow-common:
    &airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-marketdata}:${POSTGRES_PASSWORD:-marketdata}@postgres:5432/${POSTGRES_DB:-marketdb}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY:-}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    networks:
      - marketingestion

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
      -c "airflow db init && airflow users create
      --role Admin
      --username ${AIRFLOW_ADMIN_USER:-admin}
      --password ${AIRFLOW_ADMIN_PASSWORD:-airflow}
      --firstname ${AIRFLOW_ADMIN_FIRSTNAME:-Admin}
      --lastname ${AIRFLOW_ADMIN_LASTNAME:-User}
      --email ${AIRFLOW_ADMIN_EMAIL:-email}"
    restart: on-failure
    networks:
      - marketingestion

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: airflow webserver
    ports:
      - "8080:8080"
    restart: always
    networks:
      - marketingestion

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: airflow scheduler
    restart: always
    networks:
      - marketingestion

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - marketingestion

  alpaca-producer:
    build:
      context: ./producers
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python ingestion/alpaca_ingestion.py
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_TOPIC: alpaca_raw_stream
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      broker:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - marketingestion


  finnhub-producer:
    build:
      context: ./producers
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python ingestion/finnhub_ingestion.py
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_RECO_TOPIC: finnhub_raw_stream
      KAFKA_NEWS_TOPIC: finnhub_news_stream
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      broker:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - marketingestion

  alpaca-consumer:
    build:
      context: ./consumers
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python extraction/kafka_consumer_alpaca.py
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_TOPIC: alpaca_raw_stream
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      broker:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - marketingestion

  finnhub-consumer-news:
    build:
      context: ./consumers
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python extraction/kafka_consumer_finnhub_news.py
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_TOPIC: finnhub_news_stream
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      broker:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - marketingestion

  finnhub-consumer-reco:
    build:
      context: ./consumers
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python extraction/kafka_consumer_finnhub_reco.py
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_TOPIC: finnhub_raw_stream
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      broker:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - marketingestion

networks:
  marketingestion:
    driver: bridge

volumes:
  postgres_data:
