input {
  file {
    path => "/usr/share/logstash/data/market_transform01_appl.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"  
    codec => "json"
  }
}

filter {
  mutate {
    convert => { "price" => "float" }
    convert => { "size" => "float" }
    convert => { "exchange_index" => "integer" }
    convert => { "tape_index" => "integer" }
    convert => { "condition_at" => "integer" }
    convert => { "condition_i" => "integer" }
    convert => { "condition_t" => "integer" }
    convert => { "hour" => "integer" }
    convert => { "minute" => "integer" }
    convert => { "second" => "integer" }
    convert => { "day_of_week" => "integer" }
    convert => { "timestamp_epoch" => "integer" }
    convert => { "rolling_avg_price" => "float" }
    convert => { "rolling_std_price" => "float" }
    convert => { "cumulative_volume" => "float" }
  }
  date {
    match => ["timestamp_epoch", "UNIX"]
    target => "timestamp"
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://es01:9200"]
    index => "alpaca_trades_appl"
  }
}

